### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/multimodality#3]
@itchyshin to do

- [x] Exploratory analysis and data checking
- [x] Create phylogeny (talk to Losia to get relevant code)
- [x] recoding `Treatment`:  1) A, 2) O, 3) V, 4) VG, 5) VM, 6) VP, 7) VM, 8) OV, 9) AVG, 10) AVM, and 11) L. We can test all of these, but preferably we need some condensed groupings, for example, single (A, O, V, VM, VG, VP - not sure the last), double (AV, OV, AVG, AVM), triple (L).
- [x] Run an overall model with and without VCV and RVE (SMD)
- [x] Run several meta-regression: 1) comparing the number of modalities and 2) comparing simplified modalities
- [x] Run other meta-regression (@kjmathot creates a table of hypotheses)
- [x] Run publication bias test and sensitivity analyses (maybe analyses with lnRR)
- [ ] Go through the PRISMA checklist
- [x] Create a visualisation of study (data) characteristics (refer to Yefeng's code)
- [ ] Write a relevant portion of the Method section
- [ ] Write the Result section
- [x] Turn the R file to a Quarto file (more details required)
- [x] Create a webpage using the Quarto file
- [ ] Do 50 trees?
- [ ] Leave-one-study-out analyses
- [ ] Add data and missing data etc into the webpage

Add more later to make it more detailed
