### ISSUE TITLE
Final set of things-to-do

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/multimodality#9]
@itchyshin's to-do list

- [x] Create phylogeny from Jetz
- [x] Do 50 trees - combine
- [x] Creating fig with alluvial plots (a set)
- [x] Creating a world map of the study area
- [x] Create phylogeny + N
- [x] Creating fig with treatments effects + main
- [x] Creating fig trait type and duration + other key moderators
- [x] Leave-one-study-out analyses
- [x] Complete the webpage
- [x] Write a relevant portion of the Method section
- [x] Check and add to the Result section
- [x] Go through the PRISMA checklist
